pipeline {
    agent any

    stages {

        stage('Build Docker Images') {
            steps {
                dir('jarvis-devsecops') {
                    bat 'docker compose build'
                }
            }
        }

        stage('Start Containers') {
            steps {
                dir('jarvis-devsecops') {
                    bat 'docker compose up -d'
                }
            }
        }

        stage('Verify Running Containers') {
            steps {
                bat 'docker ps'
            }
        }

        stage('Stop Containers') {
            steps {
                dir('jarvis-devsecops') {
                    bat 'docker compose down'
                }
            }
        }

    }
}